const { PUBLIC_MOVIES_API_URL, PUBLIC_MOVIES_API_KEY, PUBLIC_AI_API_KEY } =
  import.meta.env;

export const MOVIES_API_URL = PUBLIC_MOVIES_API_URL;
export const MOVIES_API_KEY = PUBLIC_MOVIES_API_KEY;
export const AI_API_KEY = PUBLIC_AI_API_KEY;
